services:
  certsync:
    container_name: certsync
    user: "30000:30000"
    image: alpine:3.23
    command: ["sleep", "infinity"]
    volumes:
      - this-is-prod:/sentinel
      - caddy-certs-data:/certs
    network_mode: none
  caddy:
    container_name: caddy
    image: docker.io/nebularover77/caddy-he-cfpl@sha256:ba5684f44f85b80c87f18fb39ef8462c9a9e9d3474b474459158d5925a706af4

    build:
      context: .
    user: "30000:30000"
    restart: unless-stopped
    networks:
      shared:
      shared-ipv6:
        aliases:
          - caddy
    ports:
      - "[::]:4443:8443/tcp"
      - "[::]:4443:8443/udp"   # for HTTP/3 (optional but nice)
    volumes:
      - this-is-prod:/sentinel
      - caddy-etc-data:/etc/caddy/
      - caddy-config-data:/config
      - caddy-certs-data:/certs:ro
      - caddy-data-data:/data
networks:
  shared:
    external: true
    name: shared
  shared-ipv6:
    external: true
    name: shared-ipv6

volumes:
  this-is-prod:
    external: true
  caddy-etc-data:
    external: true
  caddy-config-data:
    external: true
  caddy-certs-data:
    external: true
  caddy-data-data:
    external: true
